### ISSUE TITLE
Optimizing for programmer time

### ISSUE THREAD

**Issue by arcuru** [phire/five_clique#2]
I don't have twitter, though this comment would better fit on there, but I think this effort is pretty cool, love unnecessarily optimizing stuff :)

I wanted to point out that if you just write the naive recursive algorithm in a compiled language you can get all the solutions in ~10 minutes of runtime on my underpowered laptop - https://github.com/patricksjackson/five_clique

I come up with the same 831 solutions starting with the same wordlist you do here.

So, the total time for getting the solution the naive way, including coding, is well under an hour.

**Comment by phire** [comment]
Yeah... I've been suspicious that the pre-calculation of neighborhoods is counterproductive.

In my experiments, I've kept the pruning and eliminated the pre-calculation of neighborhoods. This gets the PyPy version down from 5 seconds to 3.1 seconds.

But the cpython version takes longer, going from 14.5 seconds, up to 17 seconds. Cpython was really benefiting from it's optimised set intersection routine.

As for optimising for programmer time... Yes. Your solution appears to be optimal.
